### ISSUE TITLE
Implement argument parsing for pull.py

### ISSUE THREAD

**Issue by bswartwood** [ntdens/Stocks#3]
Configure and implement argument parsing for the stocks pull.py module. Ideally, the argument parser will support the following command line arguments. You will need to learn about argument parsing, providing default values, and converting arguments into objects:

1.) --stocks
A comma-separated list of stocks to query. Example: --stocks T,ATVI,MSFT
If no parameter is supplied, use T, ATVI, MSFT as defaults.

2.) --start-date / --end-date
The start and end date to pull data for each of the passed in stocks. Have start-date default to yesterday and end-date end to today (or if you can only get yesterday's data as the most recent, default to pulling just yesterday)

3.) --mode
The mode flag will control which output the program will produce. Here are some suggested values:
high - print out the highest price reached during the period
low - print out the lowest price reached during the period
last - print out the most recent price
earliest - print out the earliest price
change - print out the change between the last and the earliest
all - print out everything for each stock 

You can start with simply printing out the values and then work on producing plotly graphs if that is easier.

**Comment by ntdens** [comment]
Mission accomplished
